//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lukianov_Class.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Journal = new HashSet<Journal>();
        }
    
        public int Class_ID { get; set; }
        public string Name { get; set; }
        public int Parallel_ID { get; set; }
    
        public virtual Parallel Parallel { get; set; }
        public virtual ICollection<Journal> Journal { get; set; }
    }
}
