//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lukianov_Class.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Journal_ID { get; set; }
        public int Class_ID { get; set; }
        public string KiloFlourPaper { get; set; }
        public System.DateTime DateEvent { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
